package dtu.ws.model;

public enum EventType {
    REFUND_REQUEST,
    REFUND_FAILED,
    REFUND_SUCCEED,
    MONEY_TRANSFER_REQUEST,
    MONEY_TRANSFER_FAILED,
    MONEY_TRANSFER_SUCCEED,
    REQUEST_TRANSACTIONS,
    REQUEST_TRANSACTIONS_RESPONSE
}
